post:
  tags:
    - Product
  summary: Create Product
  description: Create a new product on your integration
  operationId: product_create
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/ProductCreate.yaml
      application/x-www-form-urlencoded:
        schema:
          $ref: ../components/schemas/ProductCreate.yaml
  responses:
    '201':
      $ref: ../components/responses/ProductCreateSuccess.yaml
    '401':
      $ref: ../components/responses/Unauthorized.yaml
    default:
      description: Server error
get:
  tags:
    - Product
  summary: List Products
  description: List all previously created products
  operationId: product_list
  parameters:
    - name: perPage
      description: Number of records to fetch per page
      in: query
      schema:
        type: integer
    - name: page
      description: The section to retrieve
      in: query
      schema:
        type: integer
    - name: active
      description: The state of the product
      in: query
      schema:
        type: boolean
      example: true
    - in: query
      name: from
      schema:
        type: string
        format: date-time
      description: The start date
    - in: query
      name: to
      schema:
        type: string
        format: date-time
      description: The end date
  responses:
    '200':
      $ref: ../components/responses/ProductListsSuccess.yaml
    '401':
      $ref: ../components/responses/Unauthorized.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
    default:
      description: Server error
