openapi: 3.0.1
info:
  title: Paystack
  description: >-
    The OpenAPI specification of the Paystack API that
    merchants and developers can harness to build financial solutions
    in Africa.
  version: 1.0.0
servers:
  - url: https://api.paystack.co
    description: Base API endpoint
tags:
  - name: Transaction
    description: >-
      The Transactions API allows you create and manage payments on your integration
    x-displayName: Transaction
  - name: Split
    description: >-
      The Transaction Splits API enables merchants split the settlement for a transaction across their payout account, and one or more subaccounts
    x-displayName: Transaction Splits
  - name: Terminal
    description: >- 
      The Terminal API allows you to build delightful in-person payment experiences
    x-displayName: Terminal
  - name: Customer
    description: >- 
      The Customers API allows you create and manage customers on your integration
    x-displayName: Customer
  - name: Dedicated Virtual Account
  - name: Subaccount
  - name: Plan
  - name: Subscription
  - name: Product
  - name: Page
  - name: Payment Request
  - name: Settlement
  - name: Transfer Recipient
  - name: Transfer
  - name: Balance
  - name: Charge
  - name: Bulk Charge
  - name: Integration
  - name: Refund
  - name: Dispute
  - name: Verification
paths:
  /transaction/initialize:
    $ref: './resources/transaction/initialize.yaml'
  /transaction/verify/{reference}:
    $ref: './resources/transaction/verify.yaml'
  /transaction:
    $ref: './resources/transaction/list.yaml'
  /transaction/{id}:
    $ref: './resources/transaction/fetch.yaml'
  /transaction/timeline/{id_or_reference}:
    $ref: './resources/transaction/timeline.yaml'
  /transaction/totals:
    $ref: './resources/transaction/totals.yaml'
  /transaction/export:
    $ref: './resources/transaction/export.yaml'
  /transaction/charge_authorization:
    $ref: './resources/transaction/charge-authorization.yaml'
  /transaction/check_authorization:
    $ref: './resources/transaction/check-authorization.yaml'
  /transaction/partial_debit:
    $ref: './resources/transaction/partial-debit.yaml'
  /transaction/{id}/event:
    $ref: './resources/transaction/event.yaml'
  /transaction/{id}/session:
    $ref: './resources/transaction/session.yaml'
  /split:
    $ref: './resources/split/index.yaml'
  /split/{id}:
    $ref: './resources/split/split-id.yaml'
  /split/{id}/subaccount/add:
    $ref: './resources/split/add-subaccount.yaml'
  /split/{id}/subaccount/remove:
    $ref: './resources/split/remove-subaccount.yaml'
  /customer:
    $ref: './resources/customer/index.yaml'
  /customer/{code}:
    $ref: './resources/customer/customer-code.yaml'
  /customer/set_risk_action:
    $ref: './resources/customer/risk-action.yaml'
  /customer/deactivate_authorization:
    $ref: './resources/customer/authorization.yaml'
  /customer/{code}/identification:
    $ref: './resources/customer/identification.yaml'
  /dedicated_account:
    $ref: './resources/dedicated-virtual-account/index.yaml'
  /dedicated_account/{account_id}:
    $ref: './resources/dedicated-virtual-account/account-id.yaml'
  /dedicated_account/available_providers:
    $ref: './resources/dedicated-virtual-account/providers.yaml'
  /dedicated_account/split:
    $ref: './resources/dedicated-virtual-account/add-split.yaml'
  /subaccount:
    $ref: './resources/subaccount/index.yaml'
  /subaccount/{code}:
    $ref: './resources/subaccount/subaccount-code.yaml'
  /plan:
    $ref: './resources/plan/index.yaml'
  /plan/{code}:
    $ref: './resources/plan/plan-code.yaml'
  /subscription:
    $ref: './resources/subscription/index.yaml'
  /subscription/{code}:
    $ref: './resources/subscription/subscription-code.yaml'
  /subscription/disable:
    $ref: './resources/subscription/disable.yaml'
  /subscription/enable:
    $ref: './resources/subscription/enable.yaml'
  /subscription/{code}/manage/link:
    $ref: './resources/subscription/manage-link.yaml'
  /subscription/{code}/manage/email:
    $ref: './resources/subscription/manage-email.yaml'
  /product:
    $ref: './resources/product/index.yaml'
  /product/{id}:
    $ref: './resources/product/product-id.yaml'
  /page:
    $ref: './resources/page/index.yaml'
  /page/{id}:
    $ref: './resources/page/page-id.yaml'
  /page/check_slug_availability/{slug}:
    $ref: './resources/page/slug-availability.yaml'
  /page/{id}/product:
    $ref: './resources/page/product.yaml'
  /paymentrequest:
    $ref: './resources/payment-request/index.yaml'
  /paymentrequest/{id}:
    $ref: './resources/payment-request/payment-request-id.yaml'
  /paymentrequest/verify/{id}:
    $ref: './resources/payment-request/verify.yaml'
  /paymentrequest/notify/{id}:
    $ref: './resources/payment-request/notify.yaml'
  /paymentrequest/totals:
    $ref: './resources/payment-request/totals.yaml'
  /paymentrequest/finalize/{id}:
    $ref: './resources/payment-request/finalize.yaml'
  /paymentrequest/archive/{id}:
    $ref: './resources/payment-request/archive.yaml'
  /settlement:
    $ref: './resources/settlement/fetch.yaml'
  /settlement/{id}/transaction:
    $ref: './resources/settlement/transaction.yaml'
  /transferrecipient:
    $ref: './resources/transfer-recipient/index.yaml'
  /transferrecipient/bulk:
    $ref: './resources/transfer-recipient/bulk.yaml'
  /transferrecipient/{code}:
    $ref: './resources/transfer-recipient/transfer-recipient-code.yaml'
  /transfer:
    $ref: './resources/transfer/index.yaml'
  /transfer/finalize_transfer:
    $ref: './resources/transfer/finalize.yaml'
  /transfer/bulk:
    $ref: './resources/transfer/bulk.yaml'
  /transfer/{code}:
    $ref: './resources/transfer/transfer-code.yaml'
  /transfer/verify/{reference}:
    $ref: './resources/transfer/verify.yaml'
  /transfer/export:
    $ref: './resources/transfer/export.yaml'
  /transfer/resend_otp:
    $ref: './resources/transfer/resend-otp.yaml'
  /transfer/disable_otp:
    $ref: './resources/transfer/disable-otp.yaml'
  /transfer/disable_otp_finalize:
    $ref: './resources/transfer/disable-otp-finalize.yaml'
  /transfer/enable_otp:
    $ref: './resources/transfer/enable-otp.yaml'
  /balance:
    $ref: './resources/balance/fetch.yaml'
  /balance/ledger:
    $ref: './resources/balance/ledger.yaml'
  /charge:
    $ref: './resources/charge/create.yaml'
  /charge/submit_pin:
    $ref: './resources/charge/submit-pin.yaml'
  /charge/submit_otp:
    $ref: './resources/charge/submit-otp.yaml'
  /charge/submit_phone:
    $ref: './resources/charge/submit-phone.yaml'
  /charge/submit_birthday:
    $ref: './resources/charge/submit-birthday.yaml'
  /charge/submit_address:
    $ref: './resources/charge/submit-address.yaml'
  /charge/{reference}:
    $ref: './resources/charge/reference.yaml'
  /bulkcharge:
    $ref: './resources/bulk-charge/index.yaml'
  /bulkcharge/{code}:
    $ref: './resources/bulk-charge/fetch.yaml'
  /bulkcharge/{code}/charges:
    $ref: './resources/bulk-charge/charges.yaml'
  /bulkcharge/pause/{code}:
    $ref: './resources/bulk-charge/pause.yaml'
  /bulkcharge/resume/{code}:
    $ref: './resources/bulk-charge/resume-charge.yaml'
  /integration/payment_session_timeout:
    $ref: './resources/integration/payment-session.yaml'
  /refund:
    $ref: './resources/refund/index.yaml'
  /refund/{id}:
    $ref: './resources/refund/fetch.yaml'
  /dispute:
    $ref: './resources/dispute/list.yaml'
  /dispute/{id}:
    $ref: './resources/dispute/dispute-id.yaml'
  /dispute/{id}/upload_url:
    $ref: './resources/dispute/upload-url.yaml'
  /dispute/export:
    $ref: './resources/dispute/export.yaml'
  /dispute/transaction/{id}:
    $ref: './resources/dispute/transaction.yaml'
  /dispute/{id}/resolve:
    $ref: './resources/dispute/resolve.yaml'
  /dispute/{id}/evidence:
    $ref: './resources/dispute/evidence.yaml'
  /bank/resolve:
    $ref: './resources/verification/resolve-bank.yaml'
  /decision/bin/{bin}:
    $ref: './resources/verification/card-bin.yaml'
  /country:
    $ref: './resources/verification/country.yaml'
  /bank:
    $ref: './resources/verification/bank.yaml'
  /address_verification/states:
    $ref: './resources/verification/state.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    Customer:
      $ref: './schemas/customer/Customer.yaml'
    Error:
      type: object
      properties:
        status:
          type:  boolean
        message:
          type: string
    Response:
      type: object
      properties:
        status:
          type:  boolean
        message:
          type: string
        data:
          type: object
  responses:
    Ok:
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: './responses/response.yaml'
    Created:
      description: Resource created
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Response'
    NotFound:
      description: Entity not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:       
            status: false
            message: Entity not found
    Unauthorized:
      description: Unauthorized operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            status: false
            message: Invalid key
    GeneralError:
      description: General Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
security:
  - bearerAuth: []