type: object
properties:
  status:
    type: boolean
  message:
    type: string
  data:
    type: array
    items:
      $ref: ./ProductListsResponseArray.yaml
  meta:
    type: object
    properties:
      total:
        type: integer
      skipped:
        type: integer
      perPage:
        type: string
      page:
        type: integer
      pageCount:
        type: integer
    required:
      - total
      - skipped
      - perPage
      - page
      - pageCount
    additionalProperties: false
required:
  - status
  - message
  - data
  - meta
