type: object
required:
  - name
  - description
  - price
  - currency
properties:
  name:
    description: Name of product
    type: string
  description:
    description: The description of the product
    type: string
  price:
    description: |
      Price should be in kobo if currency is NGN, pesewas, if currency is GHS,
      and cents, if currency is ZAR
    type: integer
  currency:
    description: |
      Currency in which price is set. Allowed values are: NGN, GHS, ZAR or USD
    type: string
  unlimited:
    description: |
      Set to true if the product has unlimited stock. Leave as false if the
      product has limited stock
    type: boolean
  quantity:
    description: Number of products in stock. Use if limited is true
    type: integer
  split_code:
    description: The split code if sharing the transaction with partners
    type: string
  metadata:
    description: Stringified JSON object of custom data
    type: string
example:
  name: Cups
  description: Environment friendly paper cups
  price: 10000
  currency: NGN