parameters:
- name: id
  in: path
  required: true
  schema:
    type: string
get:
  tags:
    - Product
  summary: Fetch Product
  operationId: product_fetch
  responses:
    200:
      $ref: '../../responses/ok.yaml'
    401:
      $ref: '../../responses/unauthorized.yaml'
    404:
      $ref: '../../responses/unauthorized.yaml'
    default:
      description: Server error
put:
  tags:
    - Product
  summary: Update product
  operationId: product_update
  requestBody:
    content:
      application/x-www-form-urlencoded:
        schema:
          $ref: '../../schemas/product/Update.yaml'
      application/json:
        schema:
          $ref: '../../schemas/product/Update.yaml'
  responses:
    200:
      $ref: '../../responses/ok.yaml'
    401:
      $ref: '../../responses/unauthorized.yaml'
    404:
      $ref: '../../responses/unauthorized.yaml'
    default:
      description: Server error
delete:
  tags:
    - Product
  summary: Delete Product
  operationId: product_delete
  responses:
    200:
      $ref: '../../responses/ok.yaml'
    401:
      $ref: '../../responses/unauthorized.yaml'
    404:
      $ref: '../../responses/unauthorized.yaml'
    default:
      description: Server error