openapi: 3.0.1
info:
  title: Create an online marketplace
  description: >-
    The OpenAPI specification for creating a marketplace application using the [Paystack API](https://paystack.com/docs/api/).
    
    ### Prerequisites

    1. Sign up on [Paystack](https://paystack.com/signup) to get your secret API key

    2. Set your API key as an environment variable on [Postman](https://learning.postman.com/docs/sending-requests/variables/)

    
    The [Split API](https://paystack.com/docs/payments/split-payments/) is useful in marketplace apps where the transactions are divided between the platform and the vendor.
    That way, the platform keeps a portion of each transaction.
  version: 1.0.0
servers:
  - url: https://api.paystack.co
    description: Base API endpoint
paths:
  /subaccount:
    post:
      $ref: '../main/resources/subaccount/create.yaml'
  /split:
    post:
      $ref: '../main/resources/split/create.yaml'
  /transaction/initialize:
    $ref: '../main/resources/transaction/initialize.yaml'
  /refund:
    post:
      $ref: '../main/resources/refund/create.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    Customer:
      $ref: '../main/schemas/customer/Customer.yaml'
    Error:
      type: object
      properties:
        status:
          type:  boolean
        message:
          type: string
    Response:
      type: object
      properties:
        status:
          type:  boolean
        message:
          type: string
        data:
          type: object
  responses:
    Ok:
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: '../main/responses/response.yaml'
    Created:
      description: Resource created
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Response'
    NotFound:
      description: Entity not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:       
            status: false
            message: Entity not found
    Unauthorized:
      description: Unauthorized operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            status: false
            message: Invalid key
    GeneralError:
      description: General Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
security:
  - bearerAuth: []